.PHONY: default clean

default:
	@cd coco; $(MAKE)
	@cd system; $(MAKE)
	@cd session; $(MAKE)
	@cd winton; $(MAKE)
	@cd newton; $(MAKE)

clean:
	cd coco; $(MAKE) clean
	cd system; $(MAKE) clean
	cd session; $(MAKE) clean
	cd winton; $(MAKE) clean
	cd newton; $(MAKE) clean
