.PHONY: default clean

default:
	@cd bar; $(MAKE)
	@cd baz; $(MAKE)
	@cd rings; $(MAKE)
	@cd triangle; $(MAKE)
	@cd breakout; $(MAKE)
	@cd mandlebrot; $(MAKE)
	@cd shell; $(MAKE)
	@cd terminal; $(MAKE)
	@cd coreutils; $(MAKE)
	@cd edit; $(MAKE)
	@cd calc; $(MAKE)
	@cd gallery; $(MAKE)

clean:
	cd bar; $(MAKE) clean
	cd baz; $(MAKE) clean
	cd rings; $(MAKE) clean
	cd triangle; $(MAKE) clean
	cd breakout; $(MAKE) clean
	cd mandlebrot; $(MAKE) clean
	cd shell; $(MAKE) clean
	cd terminal; $(MAKE) clean
	cd coreutils; $(MAKE) clean
	cd edit; $(MAKE) clean
	cd calc; $(MAKE) clean
	cd gallery; $(MAKE) clean
