.PHONY: default clean

default:
	@cd bar; $(MAKE)
	@cd baz; $(MAKE)
	@cd rings; $(MAKE)
	@cd triangle; $(MAKE)
	@cd breakout; $(MAKE)

clean:
	cd bar; $(MAKE) clean
	cd baz; $(MAKE) clean
	cd rings; $(MAKE) clean
	cd triangle; $(MAKE) clean
	cd breakout; $(MAKE) clean
